### ISSUE TITLE
Bump lowest allowed scikit-learn package version?

### ISSUE THREAD

**Issue by daholste** [microsoft/NimbusML#257]
Repro steps:
(1) Install fresh environment w/ python version 3.5.
(2) Run `pip install scikit-learn==0.19.1`
(3) Run `pip install nimbusml==1.3.0`
(3) Start Python shell, then run ```from nimbusml.feature_extraction.categorical import OneHotHashVectorizer, OneHotVectorizer```

Exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\daholste\AppData\Local\Continuum\miniconda3\envs\test35\lib\site-packages\nimbusml\__init__.py", line 26, in <module>
    from .pipeline import Pipeline
  File "C:\Users\daholste\AppData\Local\Continuum\miniconda3\envs\test35\lib\site-packages\nimbusml\pipeline.py", line 23, in <module>
    from .internal.core.base_pipeline_item import BasePipelineItem
  File "C:\Users\daholste\AppData\Local\Continuum\miniconda3\envs\test35\lib\site-packages\nimbusml\internal\core\base_pipeline_item.py", line 22, in <module>
    from nimbusml.utils import signature
  File "C:\Users\daholste\AppData\Local\Continuum\miniconda3\envs\test35\lib\site-packages\nimbusml\utils\__init__.py", line 1, in <module>
    from .utils import get_X_y, evaluate_binary_classifier, check_accuracy, \
  File "C:\Users\daholste\AppData\Local\Continuum\miniconda3\envs\test35\lib\site-packages\nimbusml\utils\utils.py", line 15, in <module>
    from sklearn.utils.testing import assert_greater
  File "C:\Users\daholste\AppData\Local\Continuum\miniconda3\envs\test35\lib\site-packages\sklearn\utils\testing.py", line 49, in <module>
    from nose.tools import raises
ImportError: No module named 'nose'
```

Mitigation:
Run `pip install scikit-learn==0.20.0`

**Comment by ganik** [comment]
The exact rootcause is this one:
\nimbusml\utils\utils.py", line 15, in <module>
    from sklearn.utils.testing import assert_greater
we should not load testing module in core production flow. We will remove this
