### ISSUE TITLE
Building for Python 3.5 fails on Windows (and other versions of Python as well)

### ISSUE THREAD

**Issue by pieths** [microsoft/NimbusML#281]
Steps to repro:
From a fresh checkout of the master branch, build with the following command:

```console
build --configuration DbgWinPy3.5 --installPythonPackages
```

This errors when trying to install the packages at the end of the build.

```console
Installing collected packages: scikit-learn
  Found existing installation: scikit-learn 0.21.3
    Uninstalling scikit-learn-0.21.3:
Exception:
Traceback (most recent call last):
  File "C:\Users\v-pischo\dev\nimbusml\fork\dependencies\Python3.5\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\users\\v-pischo\\dev\\nimbusml\\fork\\dependencies\\python3.5\\lib\\site-packages\\sklearn\\datasets\\tests\\data\\openml\\292\\api-v1-json-data-list-data_name-australian-limit-2-data_version-1-status-deactivated.json.gz' -> 'C:\\Users\\v-pischo\\AppData\\Local\\Temp\\pip-7q7n6axq-uninstall\\users\\v-pischo\\dev\\nimbusml\\fork\\dependencies\\python3.5\\lib\\site-packages\\sklearn\\datasets\\tests\\data\\openml\\292\\api-v1-json-data-list-data_name-australian-limit-2-data_version-1-status-deactivated.json.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\v-pischo\dev\nimbusml\fork\dependencies\Python3.5\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\v-pischo\dev\nimbusml\fork\dependencies\Python3.5\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\v-pischo\dev\nimbusml\fork\dependencies\Python3.5\lib\site-packages\pip\req\req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "C:\Users\v-pischo\dev\nimbusml\fork\dependencies\Python3.5\lib\site-packages\pip\req\req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "C:\Users\v-pischo\dev\nimbusml\fork\dependencies\Python3.5\lib\site-packages\pip\req\req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "C:\Users\v-pischo\dev\nimbusml\fork\dependencies\Python3.5\lib\site-packages\pip\utils\__init__.py", line 267, in renames
    shutil.move(old, new)
  File "C:\Users\v-pischo\dev\nimbusml\fork\dependencies\Python3.5\lib\shutil.py", line 558, in move
    copy_function(src, real_dst)
  File "C:\Users\v-pischo\dev\nimbusml\fork\dependencies\Python3.5\lib\shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\v-pischo\dev\nimbusml\fork\dependencies\Python3.5\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\v-pischo\\AppData\\Local\\Temp\\pip-7q7n6axq-uninstall\\users\\v-pischo\\dev\\nimbusml\\fork\\dependencies\\python3.5\\lib\\site-packages\\sklearn\\datasets\\tests\\data\\openml\\292\\api-v1-json-data-list-data_name-australian-limit-2-data_version-1-status-deactivated.json.gz'
You are using pip version 9.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

Adding the following to line 351 in build.cmd seems to fix the issue but there might be a better fix.

```console
    echo ""
    echo "#################################"
    echo "Installing python packages ... "
    echo "#################################"
    call "%PythonExe%" -m pip install --upgrade pip
```

**Comment by mstfbl** [comment]
Updated the issue to reflect Piet and Najeeb's failing builds on Python 3.6 and 2.7.
