### ISSUE TITLE
Fit() on BinaryDataStream doesnt work

### ISSUE THREAD

**Issue by ganik** [microsoft/NimbusML#304]
path = get_dataset('infert').as_filepath()
data = FileDataStream.read_csv(path)

featurization_pipeline = Pipeline([OneHotVectorizer(columns={'education': 'education'})])
featurization_pipeline.fit(data)
featurized_data = featurization_pipeline.transform(data, as_binary_data_stream=True)
#featurized_data = featurization_pipeline.transform(data)  <---- this works
 
pipeline = Pipeline([ColumnDropper() << ['case', 'row_num']])
pipeline.fit(featurized_data)

Elapsed time: 00:00:00.1407517
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    pipeline.fit(featurized_data)
  File "E:\sources\NimbusML\src\python\nimbusml\internal\utils\utils.py", line 220, in wrapper
    params = func(*args, **kwargs)
  File "E:\sources\NimbusML\src\python\nimbusml\pipeline.py", line 1154, in fit
    X, y, verbose, **params)
  File "E:\sources\NimbusML\src\python\nimbusml\pipeline.py", line 767, in _fit_graph
    strategy_iosklearn=strategy_iosklearn)
  File "E:\sources\NimbusML\src\python\nimbusml\pipeline.py", line 602, in _init_graph_nodes
    strategy_iosklearn=strategy_iosklearn)
  File "E:\sources\NimbusML\src\python\nimbusml\internal\utils\utils.py", line 220, in wrapper
    params = func(*args, **kwargs)
  File "E:\sources\NimbusML\src\python\nimbusml\pipeline.py", line 1317, in _process_transformers
    columns_out = [c for c in columns_out if
TypeError: 'NoneType' object is not iterable
Press any key to continue . . .

**Comment by pieths** [comment]
Fixed by #307
