### ISSUE TITLE
Mac Py27 build failing due to System.InvalidOperationException in NaiveBayesClassifier_df.py

### ISSUE THREAD

**Issue by mstfbl** [microsoft/NimbusML#351]
**Describe the bug**
The Mac Py27 build is failing due to a System.InvalidOperationException in NaiveBayesClassifier_df.py .

> E           RuntimeError: Issue with
> E             File '/Users/runner/runners/2.159.2/work/1/s/src/python/nimbusml/examples/examples_from_dataframe/NaiveBayesClassifier_df.py'
> E           --CMD
> E           "/Users/runner/runners/2.159.2/work/1/s/dependencies/Python2.7/bin/python" -u "/Users/runner/runners/2.159.2/work/1/s/src/python/nimbusml/examples/examples_from_dataframe/NaiveBayesClassifier_df.py"
> E           --ERR
> E           **Error: The type of column 'SentimentText' is not valid as a training feature: Vector<Single>Error: *** System.InvalidOperationException: 'Encountered 1 invalid training column(s)'Traceback (most recent call last):**
> E             File "/Users/runner/runners/2.159.2/work/1/s/src/python/nimbusml/examples/examples_from_dataframe/NaiveBayesClassifier_df.py", line 30, in <module>
> E               ppl.fit(X_train, y_train)
> E             File "<decorator-gen-9>", line 2, in fit
> E             File "/Users/runner/runners/2.159.2/work/1/s/dependencies/Python2.7/lib/python2.7/site-packages/nimbusml/internal/utils/utils.py", line 177, in trace
> E               params = func(*args, **kwargs)
> E             File "/Users/runner/runners/2.159.2/work/1/s/dependencies/Python2.7/lib/python2.7/site-packages/nimbusml/pipeline.py", line 1197, in fit
> E               raise e
> E           **nimbusml.internal.utils.entrypoints.BridgeRuntimeError: Error: *** System.InvalidOperationException: 'Encountered 1 invalid training column(s)'**
> E           --OUT
> E           Warning: Term map for output column 'SentimentText_WordExtractor' contains no entries.
> E           Elapsed time: 00:00:02.5456606

**To Reproduce**
The error is displayed [here](https://dev.azure.com/aifx/public/_build/results?buildId=1890&view=logs&j=d602e5ee-b117-53e9-baca-06d38555e9ae&t=7a4bfe99-128e-548b-1b46-3dfd9c68bb4f&l=5632).

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: Python 2.7

**Comment by mstfbl** [comment]
The ML.NET error `The type of column 'SentimentText' is not valid as a training feature: Vector<Single>` is thrown in line 193 of FeatureCombiner in Microsoft.ML.EntryPoints.

> private static List<KeyToVectorMappingEstimator.ColumnOptions> ConvertFeatures(IEnumerable<DataViewSchema.Column> feats, HashSet<string> featNames, List<KeyValuePair<string, string>> concatNames, IChannel ch,
>             out List<TypeConvertingEstimator.ColumnOptions> cvt, out int errCount)
>         {
>             Contracts.AssertValue(feats);
>             Contracts.AssertValue(featNames);
>             Contracts.AssertValue(concatNames);
>             Contracts.AssertValue(ch);
>             List<KeyToVectorMappingEstimator.ColumnOptions> ktv = null;
>             cvt = null;
>             errCount = 0;
>             foreach (var col in feats)
>             {
>                 // Skip duplicates.
>                 if (!featNames.Add(col.Name))
>                     continue;
> 
>                 if (!(col.Type is VectorDataViewType vectorType) || vectorType.Size > 0)
>                 {
>                     var type = col.Type.GetItemType();
>                     if (type is KeyDataViewType keyType)
>                     {
>                         if (keyType.Count > 0)
>                         {
>                             var colName = GetUniqueName();
>                             concatNames.Add(new KeyValuePair<string, string>(col.Name, colName));
>                             Utils.Add(ref ktv, new KeyToVectorMappingEstimator.ColumnOptions(colName, col.Name));
>                             continue;
>                         }
>                     }
>                     if (type is NumberDataViewType || type is BooleanDataViewType)
>                     {
>                         // Even if the column is R4 in training, we still want to add it to the conversion.
>                         // The reason is that at scoring time, the column might have a slightly different type (R8 for example).
>                         // This happens when the training is done on an XDF and the scoring is done on a data frame.
>                         var colName = GetUniqueName();
>                         concatNames.Add(new KeyValuePair<string, string>(col.Name, colName));
>                         Utils.Add(ref cvt, new TypeConvertingEstimator.ColumnOptions(colName, DataKind.Single, col.Name));
>                         continue;
>                     }
>                 }
> 
>                 **ch.Error("The type of column '{0}' is not valid as a training feature: {1}", col.Name, col.Type);**
>                 errCount++;
>             }
>             return ktv;
>         }

**Comment by mstfbl** [comment]
After following this wiki to build my NimbusML fork with my local ML.NET build, I've obtained the following ML.NET stack trace for this issue:

> Warning: Term map for output column 'SentimentText_WordExtractor' contains no entries.
> Error: The type of column 'SentimentText' is definitely not valid as a training feature: Vector<Single>Assertion Failed
> Assertion Failed
> 
>    at Microsoft.ML.Runtime.Contracts.DbgFailCore(String msg, IExceptionContext ctx)
>    at Microsoft.ML.Runtime.Contracts.DbgFail(IExceptionContext ctx)
>    at Microsoft.ML.Runtime.Contracts.Assert(Boolean f)
>    at Microsoft.ML.EntryPoints.FeatureCombiner.PrepareFeatures(IHostEnvironment env, FeatureCombinerInput input)
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Microsoft.ML.EntryPoints.EntryPointNode.Run()
>    at Microsoft.ML.EntryPoints.EntryPointGraph.RunNode(EntryPointNode node)
>    at Microsoft.ML.EntryPoints.GraphRunner.RunAllNonMacros()
>    at Microsoft.ML.EntryPoints.GraphRunner.RunAll()
>    at Microsoft.ML.DotNetBridge.Bridge.RunGraphCore(EnvironmentBlock* penv, IHostEnvironment env, String graphStr, Int32 cdata, DataSourceBlock** ppdata)
>    at Microsoft.ML.DotNetBridge.Bridge.GenericExec(EnvironmentBlock* penv, SByte* psz, Int32 cdata, DataSourceBlock** ppdata)
> Aborted (core dumped)

Furthermore, on Python 2.7, I saw that during this run, in FeatureCombiner.cs, the following conditions in this if-statement results in False, which triggers the error:

> `if (!(col.Type is VectorDataViewType vectorType) || vectorType.Size > 0)`

This is compared to a sample run on Python 3.6, where this if-statement results in True, and the if-statement...

> `if (type is NumberDataViewType || type is BooleanDataViewType)`

..results in True, which is the proper expected behavior. 

This means that `vectorType.Size`, which is the Vector<Single> returned in `ppl.fit(X_train, y_train)` from NaiveBayesClassifier_df.py is equal to 0.

**Comment by mstfbl** [comment]
The call parameters that are passed to the DotNetBridge and subsequently to the ML.NET side, during a run of `NaiveBayesClassifier_df.py`, at line 278 of `entrypoints.py`:

> {
>     "inputs": {
>         "input_data": ""
>     },
>     "nodes": [
>         {
>             "Inputs": {
>                 "CharFeatureExtractor": {
>                     "Name": "NGram",
>                     "Settings": {
>                         "AllLengths": false,
>                         "MaxNumTerms": [
>                             10000000
>                         ],
>                         "NgramLength": 3,
>                         "SkipLength": 0,
>                         "Weighting": "Tf"
>                     }
>                 },
>                 "Column": {
>                     "Name": "SentimentText",
>                     "Source": [
>                         "SentimentText"
>                     ]
>                 },
>                 "Data": "$input_data",
>                 "KeepDiacritics": false,
>                 "KeepNumbers": true,
>                 "KeepPunctuations": true,
>                 "Language": "English",
>                 "TextCase": "Lower",
>                 "VectorNormalizer": "None",
>                 "WordFeatureExtractor": {
>                     "Name": "NGram",
>                     "Settings": {
>                         "AllLengths": true,
>                         "MaxNumTerms": [
>                             10000000
>                         ],
>                         "NgramLength": 1,
>                         "SkipLength": 0,
>                         "Weighting": "Tf"
>                     }
>                 }
>             },
>             "Name": "Transforms.TextFeaturizer",
>             "Outputs": {
>                 "Model": "$output_model1",
>                 "OutputData": "$output_data1"
>             }
>         },
>         {
>             "Inputs": {
>                 "Column": [
>                     "Sentiment"
>                 ],
>                 "Data": "$output_data1"
>             },
>             "Name": "Transforms.OptionalColumnCreator",
>             "Outputs": {
>                 "Model": "$output_model2",
>                 "OutputData": "$optional_data"
>             }
>         },
>         {
>             "Inputs": {
>                 "Data": "$optional_data",
>                 "LabelColumn": "Sentiment",
>                 "TextKeyValues": false
>             },
>             "Name": "Transforms.LabelColumnKeyBooleanConverter",
>             "Outputs": {
>                 "Model": "$output_model3",
>                 "OutputData": "$label_data"
>             }
>         },
>         {
>             "Inputs": {
>                 "Data": "$label_data",
>                 "Features": [
>                     "SentimentText"
>                 ]
>             },
>             "Name": "Transforms.FeatureCombiner",
>             "Outputs": {
>                 "Model": "$output_model4",
>                 "OutputData": "$output_data"
>             }
>         },
>         {
>             "Inputs": {
>                 "Caching": "Auto",
>                 "FeatureColumnName": "Features",
>                 "LabelColumnName": "Sentiment",
>                 "NormalizeFeatures": "Auto",
>                 "TrainingData": "$output_data"
>             },
>             "Name": "Trainers.NaiveBayesClassifier",
>             "Outputs": {
>                 "PredictorModel": "$predictor_model"
>             }
>         },
>         {
>             "Inputs": {
>                 "PredictorModel": "$predictor_model",
>                 "TransformModels": [
>                     "$output_model1",
>                     "$output_model2",
>                     "$output_model3",
>                     "$output_model4"
>                 ]
>             },
>             "Name": "Transforms.ManyHeterogeneousModelCombiner",
>             "Outputs": {
>                 "PredictorModel": "$output_model"
>             }
>         }
>     ],
>     "outputs": {
>         "output_model": "C:\\Users\\mubal\\AppData\\Local\\Temp\\tmp9kfaxkrb.model.bin"
>     }
> }

In addition, in the call_parameters dictionary, the sentiment texts located in `call_parameters['data']` seem to be accurately stored in Python 2.7. This means the sentiment text should be getting messed up in the transformers.

**Comment by mstfbl** [comment]
This issue was caused by the variable **size** in `DataViewInterop.cpp::GetUnicodeTx` not being set to a value on non-Windows OSs. In the function that ran on all versions of Python except 3.6 on UNIX systems (`DataViewInterop.cpp::GetTX`), this size value responsible for telling the C# end (DotNetBridge) the size of the string is being set to -1. This size variable wasn't being set to anything in the managed callback function for Python 2.7. Setting it to -1 worked, as this way, the DotNetBridge understood to do a necessary utf8-utf16 conversion, which produced the correct size amount.
