### ISSUE TITLE
NGramFeaturizer2.py being skipped due to ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by mstfbl** [microsoft/NimbusML#365]
**Describe the bug**
Running NGramFeaturizer2.py produces the following error: `RuntimeError: Error: *** System.ArgumentOutOfRangeException: 'dataFile is empty`.

**To Reproduce**
Run examples/NGramFeaturizer2.py on local build.

**Build Outputs**

On Ubuntu 16 with Python 3.6 and 2.7:

>    Sentiment                                      SentimentText
> 0          1  ==RUDE== Dude, you are rude upload that carl p...
> 1          1  == OK! ==  IM GOING TO VANDALIZE WILD ONES WIK...
> 2          1  Stop trolling, zapatancas, calling me a liar m...
> 3          1  ==You're cool==  You seem like a really cool g...
> 4          1  ::::: Why are you threatening me? I'm not bein...
> Error: *** System.ArgumentOutOfRangeException: 'dataFile is empty
> Parameter name: DataFile'Traceback (most recent call last):
>   File "src/python/nimbusml/examples/NGramFeaturizer2.py", line 31, in <module>
>     features = xf.fit_transform(data)
>   File "</home/abc/.local/lib/python2.7/site-packages/decorator.pyc:decorator-gen-27>", line 2, in fit_transform
>   File "/home/abc/Documents/GitHub/NimbusML-O/dependencies/Python2.7/lib/python2.7/site-packages/nimbusml/internal/utils/utils.py", line 177, in trace
>     params = func(*args, **kwargs)
>   File "/home/abc/Documents/GitHub/NimbusML-O/dependencies/Python2.7/lib/python2.7/site-packages/nimbusml/base_transform.py", line 48, in fit_transform
>     raise e
> RuntimeError: Error: *** System.ArgumentOutOfRangeException: 'dataFile is empty
> Parameter name: DataFile'

On Windows with Python 3.6 and 2.7:

>    Sentiment                                      SentimentText
> 0          1  ==RUDE== Dude, you are rude upload that carl p...
> 1          1  == OK! ==  IM GOING TO VANDALIZE WILD ONES WIK...
> 2          1  Stop trolling, zapatancas, calling me a liar m...
> 3          1  ==You're cool==  You seem like a really cool g...
> 4          1  ::::: Why are you threatening me? I'm not bein...
> Error: *** System.ArgumentOutOfRangeException: 'dataFile is empty
> Parameter name: DataFile'Traceback (most recent call last):
>   File "src\python\nimbusml\examples\NGramFeaturizer2.py", line 31, in <module>
>     features = xf.fit_transform(data)
>   File "<C:\Users\mubal\Documents\GitHub\NimbusML-O\dependencies\Python2.7\lib\site-packages\decorator.pyc:decorator-gen-27>", line 2, in fit_transform
>   File "C:\Users\mubal\Documents\GitHub\NimbusML-O\dependencies\Python2.7\lib\site-packages\nimbusml\internal\utils\utils.py", line 177, in trace
>     params = func(*args, **kwargs)
>   File "C:\Users\mubal\Documents\GitHub\NimbusML-O\dependencies\Python2.7\lib\site-packages\nimbusml\base_transform.py", line 48, in fit_transform
>     raise e
> RuntimeError: Error: *** System.ArgumentOutOfRangeException: 'dataFile is empty
> Parameter name: DataFile'

**Desktop (please complete the following information):**
 - OS: Windows, Ubuntu
 - Python: 3.6, 2.7

**Additional context**
These build errors were reproduced locally.

**Comment by mstfbl** [comment]
NGramFeaturizer2.py is currently being skipped in test_docs_example.py due to CustomStopWordsRemover failing on the ML.NET side, as commented by @pieths on Line 90 of test_docs_example.py in PR #331 .

**Comment by mstfbl** [comment]
The fixing of this issue is currently dependent on the fixing of dotnet/machinelearning [Issue #4518](https://github.com/dotnet/machinelearning/issues/4518).

**Comment by mstfbl** [comment]
Now that Issue #4518 is fixed, this issue will be fixed and it's corresponding PR merged when the ML.NET build used by NimbusML is updated.
