### ISSUE TITLE
NgramFeaturizer+WordEmbedding throws "no supported conversion for types:" when used in conjunction with sklearn_pandas

### ISSUE THREAD

**Issue by skasturi** [Microsoft/NimbusML#97]
**Describe the bug**
NgramFeaturizer+WordEmbedding throw TypeError: no supported conversion for types: (dtype('float64'), dtype('float64'), dtype('O')) when used in conjunction with sklearn_pandas

**To Reproduce**
```
from nimbusml.preprocessing.schema import TypeConverter
from sklearn.base import BaseEstimator, TransformerMixin
from nimbusml import Pipeline
from nimbusml.datasets import get_dataset
from nimbusml.feature_extraction.text import NGramFeaturizer, WordEmbedding
from nimbusml.feature_extraction.text.extractor import Ngram
from sklearn_pandas import DataFrameMapper
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer


# data input (as a FileDataStream)
path = get_dataset('wiki_detox_train').as_filepath()
data = pd.read_csv(path, sep='\t')
class StringCastTransformer(BaseEstimator, TransformerMixin):
    """
    Cast input to string.

    The input and output type is same for this transformer.
    """

    def __init__(self, logger = None):
        """Initialize the Logger object.

        :param logger: Logger to be injected to usage in this class.
        """
        super().__init__()        

    def fit(self, x, y=None):
        """
        Fit function for string cast transform.

        :param x: Input array.
        :type x: numpy.ndarray
        :param y: Target values.
        :type y: numpy.ndarray
        :return: The instance object: self.
        """
        return self
    
    def transform(self, x):
        """
        Transform data x into array of strings.

        :param x: The data to transform.
        :type x: numpy.ndarray
        :return: The transformed data which is an array of strings.
        """
        return x.astype(str)

column = "SentimentText"
tr = []
tr.append((column,
           ([StringCastTransformer(),
                    TfidfVectorizer(use_idf=False, norm='l2', max_df=0.95, analyzer='char',
                                    ngram_range=(1, 3))]),
           {'alias': 'chargrams'}))

tr.append((column, Pipeline([NGramFeaturizer(word_feature_extractor=Ngram(weighting = 'TfIdf'))]),
           {'alias': 'wordgrams'}))

tr.append((column, 
           Pipeline([NGramFeaturizer(word_feature_extractor=Ngram(), output_tokens=True, columns={'ngram': ['SentimentText']}), 
                WordEmbedding(columns='ngram_TransformedText')]), 
           {'alias': 'wordembeddings'}))

mapper = DataFrameMapper(tr, input_df=True, sparse=True)
# fit and transform
df = pd.DataFrame(data=data, columns=[column])
features = mapper.fit_transform(data)
print(features)
```
Output

```
Traceback (most recent call last):
  File "E:\sources\NimbusML\src\python\tests\test_copyright.py", line 70, in <module>
    features = mapper.fit_transform(data)
  File "E:\sources\NimbusML\dependencies\Python3.6\lib\site-packages\sklearn_pandas\dataframe_mapper.py", line 388, in fit_transform
    return self._transform(X, y, True)
  File "E:\sources\NimbusML\dependencies\Python3.6\lib\site-packages\sklearn_pandas\dataframe_mapper.py", line 341, in _transform
    stacked = sparse.hstack(extracted).tocsr()
  File "E:\sources\NimbusML\dependencies\Python3.6\lib\site-packages\scipy\sparse\construct.py", line 465, in hstack
    return bmat([blocks], format=format, dtype=dtype)
  File "E:\sources\NimbusML\dependencies\Python3.6\lib\site-packages\scipy\sparse\construct.py", line 601, in bmat
    dtype = upcast(*all_dtypes) if all_dtypes else None
  File "E:\sources\NimbusML\dependencies\Python3.6\lib\site-packages\scipy\sparse\sputils.py", line 52, in upcast
    raise TypeError('no supported conversion for types: %r' % (args,))
TypeError: no supported conversion for types: (dtype('float64'), dtype('float32'), dtype('O'))
```

**Comment by ganik** [comment]
The issue is with this transformer chain:
```
tr.append((column, 
           Pipeline([NGramFeaturizer(word_feature_extractor=Ngram(), output_tokens=True, columns={'ngram': ['SentimentText']}), 
                WordEmbedding(columns='ngram_TransformedText')]), 
           {'alias': 'wordembeddings'}))
```
It outputs SentimentText coulmn, which is text column and is not supported by scipy sparse utils.
You should use ColumnDropper to drop this column as in below:

```
from nimbusml.preprocessing.schema import ColumnDropper

tr.append((column, 
           Pipeline([NGramFeaturizer(word_feature_extractor=Ngram(), output_tokens=True, columns={'ngram': ['SentimentText']}), 
                WordEmbedding(columns='ngram_TransformedText'), ColumnDropper() << 'SentimentText']), 
           {'alias': 'wordembeddings'}))

```
